### ISSUE TITLE
Unable to duplicate RPubs example

### ISSUE THREAD

**Issue by smach** [bhaskarvk/tilegramsR#1]
I was trying to duplicate your code here

http://rpubs.com/bhaskarvk/electoral-Map-2016

But I keep getting this error message

```
Error in derivePoints(data, lng, lat, missing(lng), missing(lat), "addMarkers") : 
  addMarkers requires non-NULL longitude/latitude values
```

I had the same problem when trying to create a tilegram using my own data with the 538 style. Any ideas?

**Comment by bhaskarvk** [comment]
I think it's because of https://github.com/rstudio/leaflet/pull/310. If you git clone rstudio/leaflet and build after merging that PR, that error should go away.

**Comment by bhaskarvk** [comment]
`devtools::install_github("rstudio/leaflet#310")` should do it, I think.

**Comment by smach** [comment]
That did the trick, thanks!

**Comment by bhaskarvk** [comment]
thanks for confirming, I will merge that PR soon.

**Comment by bhaskarvk** [comment]
The fix has now been merged in leaflet master.

**Comment by smach** [comment]
Great, thanks!
