### ISSUE TITLE
Getting an addMarkers error

### ISSUE THREAD

**Issue by elliottmorris** [bhaskarvk/tilegramsR#2]
Error in derivePoints(data, lng, lat, missing(lng), missing(lat), "addMarkers") : 
  addMarkers requires non-NULL longitude/latitude values

**Comment by bhaskarvk** [comment]
Duplicate of #1.
I merged the fix in rstudio/leaflet last night, please rebuild `devtools::install_github('rstudio/leaflet')`.

**Comment by elliottmorris** [comment]
Thanks

**Comment by elliottmorris** [comment]
Another quick question. What package is "%<>%" found in?

**Comment by bhaskarvk** [comment]
magritter, which I think is loaded automatically by dplyr or purrr

**Comment by elliottmorris** [comment]
Guess I should have updated R first....woops

Thanks again
