### ISSUE TITLE
Plotting DKOS without ME and NE congressional districts

### ISSUE THREAD

**Issue by elliottmorris** [bhaskarvk/tilegramsR#3]
Any way to use this tilegram without the congressional districts in NE & ME? 

DKOS_Electoral_College_Map_v1.states@data$trueState

**Comment by bhaskarvk** [comment]
not sure exactly what you want to do, but if you use the trueState attribute it has the same value for those states.

**Comment by elliottmorris** [comment]
Like the map on this page http://www.thecrosstab.com/stateodds/ , where the boxed on NE and ME congressional districts aren't there.

**Comment by bhaskarvk** [comment]
strange the rmapshaper::ms_disolve should have done this. I will investigate tomorrow.

**Comment by elliottmorris** [comment]
Okay! Thanks for responding after hours. And for the great code

**Comment by bhaskarvk** [comment]
Unfortunately the polygon dissolving didn't work as expected in this case. I'm afraid for now I don't see any way to accomplish this bar from doing it manually in QGIS or something.

**Comment by bhaskarvk** [comment]
If you simply don't want to plot them, I think that is doable. but merging is going to be hard.

**Comment by elliottmorris** [comment]
Could also solve the problem by having them be the same color as the statewide result. Is that doable?

**Comment by bhaskarvk** [comment]
Yes that can always be done, but you will still see the borders of the polygons, unless you set `weight=0` or `stroke=F`

**Comment by elliottmorris** [comment]
I will try this tomorrow and get back to you.

**Comment by bhaskarvk** [comment]
I think this works now. I migrated all sp classes to sf classes.
See http://rpubs.com/bhaskarvk/tilegramsR
