### ISSUE TITLE
Is it possible to create tilegrams objects by myself?

### ISSUE THREAD

**Issue by duleise** [bhaskarvk/tilegramsR#4]
Thanks for such a great work, again.
I am pretty new to map field. It looks to me the most important part of this package is the spatial objects in sf format. All examples work fine.
Unfortunately I am not in US. Is it possible to create tilegrams objects by myself? If so, is it possible to do it in R?
Thank you in advance.

**Comment by bhaskarvk** [comment]
Most of the tilegrams I have in the package came from https://github.com/PitchInteractiveInc/tilegrams. You should look at that package (which is mostly javascript) to figure out how to create a new tilegram.
I don't personally create any tilegrams, I just bundle the ones I find into this package and make them available as R sf objects.
